server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    client_max_body_size 1000000;

    error_page 404 /404.html;

    location / {
        root /tmp/www;
        #index index.html;
        allow_methods GET DELETE; # <--- Enabling DELETE here
        autoindex on;
    }

    location /uploads {
        root /tmp/www;
        allow_methods GET POST DELETE;
        autoindex on;
        upload_store /tmp/www/uploads; # <--- REQUIRED
    }

    location /cgi-bin {
        root /tmp/www;      # Where the scripts live
        allow_methods GET POST;
        autoindex on;
        cgi_extension .py;          # The extension to trigger CGI
        cgi_path /usr/bin/python3;  # The path to the interpreter 
    }
}